### ISSUE TITLE
Simplify the filters argument structure

### ISSUE THREAD

**Issue by adeverteuil** [adeverteuil/Vid#4]
Currently, each filter is a list of two items : the filter name, and the filter arguments.

```
movie:
  - - 42
    - vf:
      - - filtername
        - {argument: value, argument2: value2}
      - - filter2
        - {arg: v, arg2: v2}
```

This could be simplified as a list of mappings:

```
movie:
  - - 42
    - vf:
      - filtername: {argument: value, argument2: value2}
      - filter2: {arg: v, arg2: v2}
```
