### ISSUE TITLE
Allow overriding file format specifications

### ISSUE THREAD

**Issue by adeverteuil** [adeverteuil/Vid#8]
The output format is derived from the file extension of the output file specified with `--output`. The mapping from an extension to a list of argument to pass to ffmpeg is hardcoded.

Create a "formats" section in the YAML document which allows the user to override this default.

Example:

```
formats:
  ogv:  # One itemp per argument.
    - -f
    - ogg
    - -vcodec
    - libtheora
    - -qscale:v
    - 2
    - -acodec
    - libvorbis
    - -qscale:a
    - 1
```

Or:

```
formats:
  ogv:
    f: ogg
    vcodec: libtheora
    qscale:v: 2  # Will the first colon confuse pyyaml?
    acodec: libvorbis
    qscale:a: 1
    # What about options that don't take an argument? Use null value?
```

Things to think of:
- User input sanitation
- Error handling
